In [15]:
pip install pandas numpy matplotlib seaborn fitparse requests

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.5.1)
Requirement already satisfied: matplotlib in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.11.1)
Requirement already satisfied: seaborn in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.13.2)
Collecting fitparse
  Downloading fitparse-1.2.0.tar.gz (65 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.12/site-packages (2.32.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests) (2026.2.25)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Building wheels for collected packages: fitparse
  Building wheel for fitparse (pyproject.toml) ... done
  Created wheel for fitparse: filename=fitparse-1.2.0-py3-none-any.whl size=68276 sha256=3a4fa1b08be6ab1fef6d1b662c2c51fe5c7ba2aca6c9146271e59441cfeb3d87
  Stored in directory: /home/codespace/.cache/pip/wheels/70/74/f4/07ba357f689c8c76c09a5c6c399831b0cb3452dcc7703f304c
Successfully built fitparse
Installing collected packages: fitparse
Successfully installed fitparse-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install --upgrade pip

Requirement already satisfied: pip in /usr/local/python/3.12.1/lib/python3.12/site-packages (26.0.1)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.9 MB/s  0:00:00m eta 0:00:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.0.1
    Uninstalling pip-26.0.1:
      Successfully uninstalled pip-26.0.1
Successfully installed pip-26.2.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('strava.csv')
pd.set_option('display.max_columns', None)
df.head()

,Air Power,Cadence,Form Power,Ground Time,Leg Spring Stiffness,Power,Vertical Oscillation,altitude,cadence,datafile,distance,enhanced_altitude,enhanced_speed,fractional_cadence,heart_rate,position_lat,position_long,speed,timestamp,unknown_87,unknown_88,unknown_90
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,activities/2675855419.fit.gz,0.00,NaN,0.000,0.0,68.0,NaN,NaN,0.0,2019-07-08 21:04:03,0.0,300.0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,activities/2675855419.fit.gz,0.00,NaN,0.000,0.0,68.0,NaN,NaN,0.0,2019-07-08 21:04:04,0.0,300.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,activities/2675855419.fit.gz,1.32,NaN,1.316,0.0,71.0,NaN,NaN,1316.0,2019-07-08 21:04:07,0.0,300.0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3747.0,77.0,activities/2675855419.fit.gz,12.19,249.4,1.866,0.0,77.0,504432050.0,-999063637.0,1866.0,2019-07-08 21:04:14,0.0,100.0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3798.0,77.0,activities/2675855419.fit.gz,14.08,259.6,1.894,0.0,80.0,504432492.0,-999064534.0,1894.0,2019-07-08 21:04:15,0.0,100.0,NaN

In [6]:
df.columns

Index(['Air Power', 'Cadence', 'Form Power', 'Ground Time',
       'Leg Spring Stiffness', 'Power', 'Vertical Oscillation', 'altitude',
       'cadence', 'datafile', 'distance', 'enhanced_altitude',
       'enhanced_speed', 'fractional_cadence', 'heart_rate', 'position_lat',
       'position_long', 'speed', 'timestamp', 'unknown_87', 'unknown_88',
       'unknown_90'],
      dtype='str')

In [8]:
df.describe()

,Air Power,Cadence,Form Power,Ground Time,Leg Spring Stiffness,Power,Vertical Oscillation,altitude,cadence,distance,enhanced_altitude,enhanced_speed,fractional_cadence,heart_rate,position_lat,position_long,speed,unknown_87,unknown_88,unknown_90
count,17842.000000,17847.000000,17842.000000,17847.000000,17842.000000,17847.000000,17847.000000,14905.000000,40627.000000,40649.000000,40598.000000,40639.000000,40627.000000,38355.000000,4.045700e+04,4.045700e+04,14928.000000,40627.0,38355.000000,18618.000000
mean,1.872100,77.726565,99.485932,325.934107,13.138571,301.459797,6.458074,3846.184368,72.781254,4097.140051,271.346027,3.037084,0.070138,134.680094,5.045408e+08,-9.995175e+08,2067.483856,0.0,298.513883,-1.067354
std,2.777476,9.202077,13.866222,71.773687,2.039567,48.540552,1.135497,134.262498,17.743728,5827.964663,25.035768,1.959805,0.173639,18.713782,1.690905e+05,1.376341e+06,527.173476,0.0,17.176218,2.820492
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3555.000000,0.000000,0.000000,209.000000,0.000000,0.000000,56.000000,5.039868e+08,-1.005696e+09,0.000000,0.0,100.000000,-13.000000
25%,1.000000,78.000000,97.000000,308.000000,13.000000,283.000000,6.125000,3768.000000,74.000000,1117.970000,252.800000,2.109000,0.000000,121.000000,5.044397e+08,-9.993986e+08,1782.000000,0.0,300.000000,-3.000000
50%,1.000000,79.000000,101.000000,326.000000,13.375000,303.000000,6.500000,3829.000000,78.000000,2430.500000,269.200000,2.445000,0.000000,136.000000,5.045116e+08,-9.992608e+08,2071.000000,0.0,300.000000,0.000000
75%,2.000000,80.000000,105.000000,340.000000,13.750000,326.000000,7.000000,3912.000000,80.000000,4403.730000,291.200000,2.809000,0.000000,148.000000,5.046159e+08,-9.990579e+08,2370.000000,0.0,300.000000,0.000000
max,48.000000,88.000000,125.000000,1732.000000,16.875000,462.000000,12.500000,5043.000000,118.000000,39007.120000,508.600000,15.349000,0.500000,183.000000,5.089272e+08,-9.921938e+08,7744.000000,0.0,300.000000,6.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40649 entries, 0 to 40648
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Air Power             17842 non-null  float64
 1   Cadence               17847 non-null  float64
 2   Form Power            17842 non-null  float64
 3   Ground Time           17847 non-null  float64
 4   Leg Spring Stiffness  17842 non-null  float64
 5   Power                 17847 non-null  float64
 6   Vertical Oscillation  17847 non-null  float64
 7   altitude              14905 non-null  float64
 8   cadence               40627 non-null  float64
 9   datafile              40649 non-null  str
 10  distance              40649 non-null  float64
 11  enhanced_altitude     40598 non-null  float64
 12  enhanced_speed        40639 non-null  float64
 13  fractional_cadence    40627 non-null  float64
 14  heart_rate            38355 non-null  float64
 15  position_lat          40457 non-null  float64
 16  position_long         40457 non-null  float64
 17  speed                 14928 non-null  float64
 18  timestamp             40649 non-null  str
 19  unknown_87            40627 non-null  float64
 20  unknown_88            38355 non-null  float64
 21  unknown_90            18618 non-null  float64
dtypes: float64(20), str(2)
memory usage: 6.8 MB

In [10]:
df['timestamp_dt'] = pd.to_datetime(df['timestamp'], unit='s')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40649 entries, 0 to 40648
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Air Power             17842 non-null  float64
 1   Cadence               17847 non-null  float64
 2   Form Power            17842 non-null  float64
 3   Ground Time           17847 non-null  float64
 4   Leg Spring Stiffness  17842 non-null  float64
 5   Power                 17847 non-null  float64
 6   Vertical Oscillation  17847 non-null  float64
 7   altitude              14905 non-null  float64
 8   cadence               40627 non-null  float64
 9   datafile              40649 non-null  str
 10  distance              40649 non-null  float64
 11  enhanced_altitude     40598 non-null  float64
 12  enhanced_speed        40639 non-null  float64
 13  fractional_cadence    40627 non-null  float64
 14  heart_rate            38355 non-null  float64
 15  position_lat          40457 non-null  float64
 16  position_long         40457 non-null  float64
 17  speed                 14928 non-null  float64
 18  timestamp             40649 non-null  str
 19  unknown_87            40627 non-null  float64
 20  unknown_88            38355 non-null  float64
 21  unknown_90            18618 non-null  float64
 22  timestamp_dt          40649 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(20), str(2)
memory usage: 7.1 MB

In [11]:
df.sample()

,Air Power,Cadence,Form Power,Ground Time,Leg Spring Stiffness,Power,Vertical Oscillation,altitude,cadence,datafile,distance,enhanced_altitude,enhanced_speed,fractional_cadence,heart_rate,position_lat,position_long,speed,timestamp,unknown_87,unknown_88,unknown_90,timestamp_dt
37129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0,activities/2904156632.fit.gz,1462.05,255.6,9.452,0.0,131.0,504500433.0,-999294756.0,NaN,2019-09-25 21:49:41,0.0,300.0,NaN,2019-09-25 21:49:41

In [13]:
# access extra data in .tar.gz folder
import io
import requests
import tarfile

url = "https://github.com/vandao288/strava_data_report/raw/main/extra.tar.gz"

response = requests.get(url)
# Open the downloaded stream as a gzipped tar archive ('r:gz')
with tarfile.open(fileobj=io.BytesIO(response.content), mode="r:gz") as tar:
    # List all file names in the archive
    print(tar.getnames())
    
    # Extract to a local directory
    tar.extractall("./extra_data")

['extra', 'extra/2688518063.fit', 'extra/2694503189.fit', 'extra/2878165145.fit', 'extra/2934415201.fit', 'extra/2875543445.fit', 'extra/4202632408.fit', 'extra/4431076868.fit', 'extra/3220821481.fit', 'extra/2677659014.fit', 'extra/2737470737.fit', 'extra/3037049993.fit', 'extra/2725350599.fit', 'extra/4262319929.fit', 'extra/4233198342.fit', 'extra/2939549086.fit', 'extra/2694503073.fit', 'extra/4449332433.fit', 'extra/2749660320.fit', 'extra/3276319440.fit', 'extra/3573233193.fit', 'extra/4116838134.fit', 'extra/2791022871.fit', 'extra/4116832581.fit', 'extra/2700298434.fit', 'extra/2796808375.fit', 'extra/4182662451.fit', 'extra/2711850942.fit', 'extra/4223086640.fit', 'extra/2912139332.fit', 'extra/3589053594.fit', 'extra/2829934608.fit', 'extra/3094198881.fit', 'extra/3747633909.fit', 'extra/3744072620.fit', 'extra/4380955548.fit', 'extra/4171121567.fit', 'extra/2749724556.fit', 'extra/4151263436.fit', 'extra/3964368444.fit', 'extra/3456057777.fit', 'extra/3790627836.fit', 'extra/2705646131.fit', 'extra/2704852906.fit', 'extra/4212667645.fit', 'extra/4421819491.fit', 'extra/4343322499.fit', 'extra/4388825966.fit', 'extra/4188711652.fit', 'extra/3022993168.fit', 'extra/2770194670.fit', 'extra/3485522419.fit', 'extra/4473390238.fit', 'extra/3494550265.fit', 'extra/3527025919.fit', 'extra/2903714629.fit', 'extra/2808772306.fit', 'extra/4440341601.fit', 'extra/3010932933.fit', 'extra/2796644542.fit', 'extra/3948465271.fit', 'extra/4186809229.fit', 'extra/2677658978.fit', 'extra/4199825713.fit', 'extra/3715967290.fit', 'extra/2903861013.fit', 'extra/3599202919.fit', 'extra/4353812160.fit', 'extra/4133816421.fit', 'extra/4463447476.fit', 'extra/3676791181.fit', 'extra/3804121662.fit', 'extra/4193952062.fit', 'extra/3012243280.fit', 'extra/2764416704.fit', 'extra/3012260245.fit', 'extra/3042255479.fit', 'extra/3822637712.fit', 'extra/3129840680.fit', 'extra/4482079599.fit', 'extra/4373850380.fit', 'extra/3643248380.fit', 'extra/2944662710.fit', 'extra/4184241616.fit', 'extra/2871922778.fit', 'extra/4390898822.fit', 'extra/2786247269.fit', 'extra/2717598473.fit', 'extra/2755618021.fit', 'extra/2740274713.fit', 'extra/3256620355.fit', 'extra/3358278926.fit', 'extra/2758868351.fit', 'extra/2682705331.fit', 'extra/4264439094.fit', 'extra/2728413477.fit', 'extra/4202467040.fit', 'extra/3971899690.fit', 'extra/2931377508.fit', 'extra/3547030788.fit', 'extra/4363446537.fit', 'extra/3443104082.fit', 'extra/2871866640.fit', 'extra/3613767195.fit', 'extra/4402182290.fit', 'extra/2742761748.fit', 'extra/4284828228.fit', 'extra/4237655169.fit', 'extra/4412654958.fit', 'extra/2729896401.fit', 'extra/3909164583.fit', 'extra/2758776303.fit', 'extra/4491335236.fit', 'extra/3604153297.fit', 'extra/3138992113.fit', 'extra/2803436608.fit', 'extra/4171524844.fit', 'extra/4224892630.fit', 'extra/4459004581.fit', 'extra/4310754259.fit', 'extra/2979902963.fit', 'extra/3352743076.fit', 'extra/3631494433.fit', 'extra/4215131133.fit', 'extra/4252845958.fit', 'extra/3813961777.fit', 'extra/2711550627.fit', 'extra/3625902324.fit', 'extra/4149983338.fit', 'extra/3795944047.fit', 'extra/2675855419.fit', 'extra/3870791458.fit', 'extra/2697793360.fit', 'extra/3141599857.fit', 'extra/4393383298.fit', 'extra/3333546324.fit', 'extra/2797454257.fit', 'extra/2797307100.fit', 'extra/2722642748.fit', 'extra/2779207820.fit', 'extra/2863488401.fit', 'extra/3389056073.fit', 'extra/3732175961.fit', 'extra/3747582080.fit', 'extra/3919978068.fit', 'extra/3772423862.fit', 'extra/4378842161.fit', 'extra/2917827233.fit', 'extra/4328087309.fit', 'extra/4272423040.fit', 'extra/2697739124.fit', 'extra/3854017510.fit', 'extra/3342969743.fit', 'extra/2752548971.fit', 'extra/2717660588.fit', 'extra/2708973950.fit', 'extra/3240280195.fit', 'extra/2984912780.fit', 'extra/4293881393.fit', 'extra/3471843956.fit', 'extra/3557109848.fit', 'extra/3660689066.fit', 'extra/3830596655.fit', 'extra/2875620974.fit', 'extra/2688898988.fit', 'extra/2898932854.fit', 'extra/4204676229.fit', 'extra/4323063597.fit', 'extra/2737527405.fit', 'extra/4282634337.fit', 'extra/3463825416.fit', 'extra/3692215284.fit', 'extra/4338280842.fit', 'extra/2925939753.fit', 'extra/3814796349.fit', 'extra/2904156632.fit', 'extra/3406746710.fit', 'extra/2737403219.fit', 'extra/2821406438.fit', 'extra/4308435182.fit', 'extra/4345550183.fit', 'extra/2772917919.fit', 'extra/3017535114.fit', 'extra/3877183540.fit', 'extra/2746000812.fit', 'extra/3761442379.fit', 'extra/2734269580.fit', 'extra/3273475816.fit', 'extra/2972237626.fit', 'extra/3915196372.fit', 'extra/2677658993.fit', 'extra/4318061779.fit', 'extra/3933111063.fit', 'extra/3648922417.fit', 'extra/2764107892.fit', 'extra/3003753171.fit', 'extra/3211480902.fit', 'extra/3383265916.fit', 'extra/2953326259.fit', 'extra/3892809878.fit']

In [18]:
# try to look into fit file in extra data
from fitparse import FitFile

fit_file_path = './extra_data/extra/2688518063.fit'
fitfile = FitFile(fit_file_path)
my_data = fitfile.get_messages('record')

In [19]:
type(my_data)

generator

In [24]:
first_record = next(fitfile.get_messages("record"))

for data in first_record:
    print(data)
    #print(f"Field: {data.name} | Value: {data.value} | Units: {data.units}")

altitude: 258.0 [m]
cadence: 74 [rpm]
distance: 1.27 [m]
enhanced_altitude: 258.0 [m]
enhanced_speed: 1.885 [m/s]
fractional_cadence: 0.5 [rpm]
heart_rate: 103 [bpm]
position_lat: 504427594 [semicircles]
position_long: -998947981 [semicircles]
speed: 1.885 [m/s]
timestamp: 2019-07-14 17:20:28
unknown_87: 0
unknown_88: 300